## Pandas

In [4]:
import requests
import pandas as pd
import numpy as np

In [5]:
url = "https://raw.githubusercontent.com/bcarcamo91/DS-Main/main/Albums/TopSellingAlbums.csv"

In [6]:
df = pd.read_csv(url)
df.head()

Artist                      Album  Released   Length   
0  Michael Jackson                   Thriller      1982  0:42:19  \
1            AC/DC              Back in Black      1980  0:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  0:42:49   
3  Whitney Houston              The Bodyguard      1992  0:57:44   
4        Meat Loaf            Bat Out of Hell      1977  0:46:33   

                         Genre  Music Recording Sales (millions)   
0               pop, rock, R&B                              46.0  \
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65  30-Nov-82        NaN    10.0  
1                        50  25-Jul-80        NaN     9.5  
2                        45  01-Mar-73        NaN     9.0  
3                        44  17-Nov-92          Y     8.5  
4                        43  21-Oct-77        NaN     8.0

In [8]:
#Access to the column length and assign it to a new dataframe x
x = df[['Length']]
print(x)

    Length
0  0:42:19
1  0:42:11
2  0:42:49
3  0:57:44
4  0:46:33
5  0:43:08
6  1:15:54
7  0:40:01


In [10]:
#Get the column as a series
x = df['Length']
print(x)

0    0:42:19
1    0:42:11
2    0:42:49
3    0:57:44
4    0:46:33
5    0:43:08
6    1:15:54
7    0:40:01
Name: Length, dtype: object


In [11]:
#Access to multiple columns
y = df[['Artist','Length','Genre']]
y

Artist   Length                        Genre
0  Michael Jackson  0:42:19               pop, rock, R&B
1            AC/DC  0:42:11                    hard rock
2       Pink Floyd  0:42:49             progressive rock
3  Whitney Houston  0:57:44               R&B, soul, pop
4        Meat Loaf  0:46:33  hard rock, progressive rock
5           Eagles  0:43:08   rock, soft rock, folk rock
6         Bee Gees  1:15:54                        disco
7    Fleetwood Mac  0:40:01                    soft rock

In [12]:
# Access the value on the first row and the first column
df.iloc[0, 0]

'Michael Jackson'

In [13]:
# Access the value on the second row and the first column
df.iloc[1,0]

'AC/DC'

In [14]:
# Access the value on the second row and the third column
df.iloc[1,2]

1980

In [15]:
#You can also access the column using the name
df.loc[1, 'Artist']

'AC/DC'

In [16]:
#Access the column using the name
df.loc[1, 'Artist']

'AC/DC'

In [17]:
#Access the column using the name
df.loc[0, 'Released']

1982

In [18]:
#Access the column using the name
df.loc[1, 'Released']

1980

In [19]:
#Slicing the dataframe
df.iloc[0:2, 0:3]

Artist          Album  Released
0  Michael Jackson       Thriller      1982
1            AC/DC  Back in Black      1980

In [21]:
#Slicing the dataframe using name
df.loc[0:2, 'Artist':'Released']

Artist                      Album  Released
0  Michael Jackson                   Thriller      1982
1            AC/DC              Back in Black      1980
2       Pink Floyd  The Dark Side of the Moon      1973

In [23]:
#Use a variable q to store the column Rating as a dataframe
q = df[['Rating']]

   Rating
0    10.0
1     9.5
2     9.0
3     8.5
4     8.0
5     7.5
6     7.0
7     6.5


In [26]:
#Write your code below and press Shift+Enter to execute
q = df[['Released', 'Artist']]
print(q)

   Released           Artist
0      1982  Michael Jackson
1      1980            AC/DC
2      1973       Pink Floyd
3      1992  Whitney Houston
4      1977        Meat Loaf
5      1976           Eagles
6      1977         Bee Gees
7      1977    Fleetwood Mac


In [27]:
print(df.iloc[1, 2])

1980


In [ ]:
df_new = df
df_new.index = new_index
df_new.oc['a', 'Artist']
df_new.loc['a':'d', 'Artist']

## 2D NumPy in Python

In [30]:
#Import the libraries
import numpy as np 
import matplotlib.pyplot as plt

In [31]:
#Create a list
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [32]:
#Convert list to Numpy Array
#Every element is the same type
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [33]:
#Show the numpy array dimensions
A.ndim

2

In [34]:
#Show the numpy array shape
A.shape

(3, 3)

In [35]:
#Show the numpy array size
A.size

9

## Accessing different elements of a NumPy array

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="500">

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400">


In [39]:
#Access the element on the second row and third column
A[1, 2]

23

In [40]:
#Access the element on the second row and third column
A[1][2]

23

In [41]:
#Access the element on the first row and first column
A[0][0]

11

In [42]:
#Access the element on the first row and first and second columns
A[0][0:2]

array([11, 12])

In [43]:
#Access the element on the first and second rows and third column
A[0:2, 2]

array([13, 23])

In [44]:
#Create a numpy array X
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [45]:
#Create a numpy array Y
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [46]:
#Add X and Y
Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [47]:
#Create a numpy array Y
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [48]:
#Multiply Y with 2
Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [49]:
#Create a numpy array Y
Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [50]:
#Create a numpy array X
X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [51]:
#Multiply X with Y
Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [52]:
#Create a matrix A
A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [53]:
#Create a matrix B
B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [54]:
#Calculate the dot product
Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [55]:
#Calculate the sine of Z
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [56]:
#Create a matrix C
C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [57]:
#Get the transposed of C
C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [58]:
#Convert list a to a numpy array
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)

In [59]:
#Calculate the numpy array size
A.size

12

In [60]:
#Access the element on the firs row and first and second columns
A[0][0:2]

array([1, 2])

In [63]:
#Perform matrix multiplication with the numpy arrays A and B
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
X = np.dot(A,B)

## Selecting data in DF

In [64]:
# let us import the Pandas Library
import pandas as pd

In [65]:
#Define a dictionary 'x'

x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}

#casting the dictionary to a DataFrame
df = pd.DataFrame(x)

#display the result df
df

Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [66]:
#Retrieving the "ID" column and assigning it to a variable x
x = df[['ID']]
x

ID
0   1
1   2
2   3
3   4

In [68]:
#check the type of x
type(x)

pandas.core.frame.DataFrame

In [69]:
#Retrieving the Department, Salary and ID columns and assigning it to a variable z

z = df[['Department','Salary','ID']]
z

Department  Salary  ID
0  Architect Group  100000   1
1   Software Group   80000   2
2      Design Team   50000   3
3   Infrastructure   60000   4

In [73]:
dict = {'Student': ['David', 'Samuel', 'Terry', 'Evan'], 'Age': [27, 24, 22, 23], 'Country': ['UK', 'Canada', 'China', 'USA'], 'Course': ['Python', 'Data Structures', 'Machine Learning', 'Web Development'], 'Marks': [85, 72, 89, 76]}
df = pd.DataFrame(dict)

print(df)

  Student  Age Country            Course  Marks
0   David   27      UK            Python     85
1  Samuel   24  Canada   Data Structures     72
2   Terry   22   China  Machine Learning     89
3    Evan   23     USA   Web Development     76


In [76]:
#Assign Marks column to variable b
b = df[['Marks']]
b

Marks
0     85
1     72
2     89
3     76

In [77]:
#Assign country and course column to variable c
c = df[['Country', 'Course']]
print(c)

  Country            Course
0      UK            Python
1  Canada   Data Structures
2   China  Machine Learning
3     USA   Web Development


In [80]:
#Assign as a series to variable x
x = df['Student']

In [81]:
#Verify that x is a series
type(x)

pandas.core.series.Series